version: '2.4'
services:
  #https://hub.docker.com/_/zookeeper
  zk1:
    build: zookeeper
    container_name: '${COMPOSE_PROJECT_NAME}_zk1'
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr,conf,ruok
      ZOO_AUTOPURGE_PURGEINTERVAL: 1
    ports:
      - 2181:2181
    volumes:
      - 'zk1_data:/data'
      - 'zk1_data_log:/datalog'
    networks:
      - solr
    restart: '${CONTAINER_RESTART}'

  zk2:
    build: zookeeper
    container_name: '${COMPOSE_PROJECT_NAME}_zk2'
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr,conf,ruok
      ZOO_AUTOPURGE_PURGEINTERVAL: 1
    ports:
      - 2182:2181
    volumes:
      - 'zk2_data:/data'
      - 'zk2_data_log:/datalog'
    networks:
      - solr
    restart: '${CONTAINER_RESTART}'

  zk3:
    build: zookeeper
    container_name: '${COMPOSE_PROJECT_NAME}_zk3'
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr,conf,ruok
      ZOO_AUTOPURGE_PURGEINTERVAL: 1
    ports:
      - 2183:2181
    volumes:
      - 'zk3_data:/data'
      - 'zk3_data_log:/datalog'
    networks:
      - solr
    restart: '${CONTAINER_RESTART}'

  solr1:
    build: solr
    container_name: '${COMPOSE_PROJECT_NAME}_solr1'
    environment:
      - SOLR_HEAP
      - SOLR_HOST=solr1
      - ZK_HOST=zk1:2181,zk2:2181,zk3:2181
    ports:
      - 8983:8983
    volumes:
      - 'solr_data1:/var/solr'
      - 'solr_share:/share'
    networks:
      - solr
    restart: '${CONTAINER_RESTART}'

  solr2:
    build: solr
    container_name: '${COMPOSE_PROJECT_NAME}_solr2'
    environment:
      - SOLR_HEAP
      - SOLR_HOST=solr2
      - ZK_HOST=zk1:2181,zk2:2181,zk3:2181
    ports:
      - 8984:8983
    volumes:
      - 'solr_data2:/var/solr'
      - 'solr_share:/share'
    networks:
      - solr
    restart: '${CONTAINER_RESTART}'

  solr3:
    build: solr
    container_name: '${COMPOSE_PROJECT_NAME}_solr3'
    environment:
      - SOLR_HEAP
      - SOLR_HOST=solr3
      - ZK_HOST=zk1:2181,zk2:2181,zk3:2181
    ports:
      - 8985:8983
    volumes:
      - 'solr_data3:/var/solr'
      - 'solr_share:/share'
    networks:
      - solr
    restart: '${CONTAINER_RESTART}'

  solr4:
    build: solr
    container_name: '${COMPOSE_PROJECT_NAME}_solr4'
    environment:
      - SOLR_HEAP
      - SOLR_HOST=solr4
      - ZK_HOST=zk1:2181,zk2:2181,zk3:2181
    ports:
      - 8986:8983
    volumes:
      - 'solr_data4:/var/solr'
      - 'solr_share:/share'
    networks:
      - solr
    restart: '${CONTAINER_RESTART}'

volumes:
  zk1_data:
    driver: local
  zk1_data_log:
    driver: local
  zk2_data:
    driver: local
  zk2_data_log:
    driver: local
  zk3_data:
    driver: local
  zk3_data_log:
    driver: local
  solr_data1:
    driver: local
  solr_data2:
    driver: local
  solr_data3:
    driver: local
  solr_data4:
    driver: local
  solr_share:
    driver: local

networks:
  solr:
    name: '${COMPOSE_PROJECT_NAME}_solr'
    driver: bridge
