version: '2.4'
services:
  solr-stda-1:
    build: solr
    container_name: '${COMPOSE_PROJECT_NAME}_solr_stda_1'
    environment:
      - SOLR_HEAP
      - SOLR_HOST=solr1
    ports:
      - 8983:8983
    extra_hosts:
      - "solr1:127.0.0.1"
    volumes:
      - './solr/solr${SOLR_VERSION}/solr.xml:/var/solr/solr.xml'
      - './solr/solr${SOLR_VERSION}/solr.in.sh:/etc/default/solr.in.sh'
      - 'solr_stda_data1:/var/solr'
      - './share:/share'
    networks:
      - solr_stda
    restart: '${CONTAINER_RESTART}'
    
  solr-stda-2:
    build: solr
    container_name: '${COMPOSE_PROJECT_NAME}_solr_stda_2'
    environment:
      - SOLR_HEAP
      - SOLR_HOST=solr2
    ports:
      - 8984:8983
    extra_hosts:
      - "solr2:127.0.0.1"
    volumes:
      - './solr/solr${SOLR_VERSION}/solr.xml:/var/solr/solr.xml'
      - './solr/solr${SOLR_VERSION}/solr.in.sh:/etc/default/solr.in.sh'
      - 'solr_stda_data2:/var/solr'
      - './share:/share'
    networks:
      - solr_stda
    restart: '${CONTAINER_RESTART}'

volumes:
  solr_stda_data1:
    driver: local
  solr_stda_data2:
    driver: local


networks:
  solr_stda:
    name: '${COMPOSE_PROJECT_NAME}_solr_stda'
    driver: bridge

    