version: '2.4'
services:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 9080:9000
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: '${CONTAINER_RESTART}'

volumes:
  portainer_data:
    driver: local
